import { useReducer } from 'react';

const initialState = {
  prompt: '',
  provider: 'huggingface-ltx',
  duration: 2,
  ratio: '16:9',
  framing: 'medium shot',
  cameraMovement: 'slow push-in',
  lighting: 'natural cinematic',
  status: 'Ready',
  result: null,
  showSettings: false,
  showWorkspaceMenu: false,
  showGenerationControls: false,
  providers: [],
  generating: false,
  referenceGenerationId: null,
  mediaFormats: [],
  selectedFormat: 'cinematic',
  genre: 'action',
  formatPlan: null,
  planning: false,
  formatMenuOpen: false,
  showShotControls: false,
  filmMode: false,
  filmIdea: '',
  filmAssist: null,
  assisting: false,
  filmProjects: [],
  filmProjectId: '',
  filmProject: null,
  shotDraft: { sceneId: '', framing: 'medium shot', angle: 'eye level', movement: 'static', lens: '35mm', lighting: 'natural cinematic', audio: 'production sound', description: '' },
  takeDraft: { camera: '', lens: '35mm', fps: 24, shutter: '1/48', iso: '400', whiteBalance: '5600K', location: '', mediaUri: '', notes: '' },
  filmTab: 'shots',
  filmReview: null,
  continuityReport: null,
  assetUploadShotId: '',
  uploadingAsset: false,
  storyDraft: { premise: '', theme: '', tone: '', setting: '', rules: '', locations: '', factions: '', terminology: '' },
  characterDraft: { name: '', role: '', appearance: '', personality: '', description: '' },
  selectedSceneId: '',
  sceneDraft: { title: '', location: '', timeOfDay: '', dramaticBeat: '', characters: '', blocking: '', action: '', dialogue: '', mood: '', weather: '', props: '', description: '' },
  productionTool: '',
  editDraft: { shotId: '', trimIn: 0, trimOut: 0, speed: 1, transition: 'cut', volume: 100 },
  effectDraft: { effect: 'none', intensity: 50, background: 'original', overlay: '', stabilization: false },
  audioDraft: { dialogue: 100, music: 70, sfx: 100, ambience: 80 },
  workspaceTool: '',
  route: window.location.pathname || '/generator',
  density: localStorage.getItem('cinematic-density') || 'comfortable',
  notice: null,
  progress: 0,
  selectedLayer: 'base',
  jobCost: null,
  activeJobId: null,
  retryJobId: null,
  authenticated: false,
  authReady: false,
  loginPassword: '',
  loginEmail: '',
  loginError: '',
  authMode: 'login',
};

function reducer(state, action) {
  if (action.type !== 'set') return state;
  const value = typeof action.value === 'function'
    ? action.value(state[action.key])
    : action.value;
  return { ...state, [action.key]: value };
}

export function useAppState() {
  const [state, dispatch] = useReducer(reducer, initialState);
  return {
    prompt: state.prompt,
    provider: state.provider,
    duration: state.duration,
    ratio: state.ratio,
    framing: state.framing,
    cameraMovement: state.cameraMovement,
    lighting: state.lighting,
    status: state.status,
    result: state.result,
    showSettings: state.showSettings,
    showWorkspaceMenu: state.showWorkspaceMenu,
    showGenerationControls: state.showGenerationControls,
    providers: state.providers,
    generating: state.generating,
    referenceGenerationId: state.referenceGenerationId,
    mediaFormats: state.mediaFormats,
    selectedFormat: state.selectedFormat,
    genre: state.genre,
    formatPlan: state.formatPlan,
    planning: state.planning,
    formatMenuOpen: state.formatMenuOpen,
    showShotControls: state.showShotControls,
    filmMode: state.filmMode,
    filmIdea: state.filmIdea,
    filmAssist: state.filmAssist,
    assisting: state.assisting,
    filmProjects: state.filmProjects,
    filmProjectId: state.filmProjectId,
    filmProject: state.filmProject,
    shotDraft: state.shotDraft,
    takeDraft: state.takeDraft,
    filmTab: state.filmTab,
    filmReview: state.filmReview,
    continuityReport: state.continuityReport,
    assetUploadShotId: state.assetUploadShotId,
    uploadingAsset: state.uploadingAsset,
    storyDraft: state.storyDraft,
    characterDraft: state.characterDraft,
    selectedSceneId: state.selectedSceneId,
    sceneDraft: state.sceneDraft,
    productionTool: state.productionTool,
    editDraft: state.editDraft,
    effectDraft: state.effectDraft,
    audioDraft: state.audioDraft,
    workspaceTool: state.workspaceTool,
    route: state.route,
    density: state.density,
    notice: state.notice,
    progress: state.progress,
    selectedLayer: state.selectedLayer,
    jobCost: state.jobCost,
    activeJobId: state.activeJobId,
    retryJobId: state.retryJobId,
    authenticated: state.authenticated,
    authReady: state.authReady,
    loginPassword: state.loginPassword,
    loginEmail: state.loginEmail,
    loginError: state.loginError,
    authMode: state.authMode,
    setPrompt: value => dispatch({ type: 'set', key: 'prompt', value }),
    setProvider: value => dispatch({ type: 'set', key: 'provider', value }),
    setDuration: value => dispatch({ type: 'set', key: 'duration', value }),
    setRatio: value => dispatch({ type: 'set', key: 'ratio', value }),
    setFraming: value => dispatch({ type: 'set', key: 'framing', value }),
    setCameraMovement: value => dispatch({ type: 'set', key: 'cameraMovement', value }),
    setLighting: value => dispatch({ type: 'set', key: 'lighting', value }),
    setStatus: value => dispatch({ type: 'set', key: 'status', value }),
    setResult: value => dispatch({ type: 'set', key: 'result', value }),
    setShowSettings: value => dispatch({ type: 'set', key: 'showSettings', value }),
    setShowWorkspaceMenu: value => dispatch({ type: 'set', key: 'showWorkspaceMenu', value }),
    setShowGenerationControls: value => dispatch({ type: 'set', key: 'showGenerationControls', value }),
    setProviders: value => dispatch({ type: 'set', key: 'providers', value }),
    setGenerating: value => dispatch({ type: 'set', key: 'generating', value }),
    setReferenceGenerationId: value => dispatch({ type: 'set', key: 'referenceGenerationId', value }),
    setMediaFormats: value => dispatch({ type: 'set', key: 'mediaFormats', value }),
    setSelectedFormat: value => dispatch({ type: 'set', key: 'selectedFormat', value }),
    setGenre: value => dispatch({ type: 'set', key: 'genre', value }),
    setFormatPlan: value => dispatch({ type: 'set', key: 'formatPlan', value }),
    setPlanning: value => dispatch({ type: 'set', key: 'planning', value }),
    setFormatMenuOpen: value => dispatch({ type: 'set', key: 'formatMenuOpen', value }),
    setShowShotControls: value => dispatch({ type: 'set', key: 'showShotControls', value }),
    setFilmMode: value => dispatch({ type: 'set', key: 'filmMode', value }),
    setFilmIdea: value => dispatch({ type: 'set', key: 'filmIdea', value }),
    setFilmAssist: value => dispatch({ type: 'set', key: 'filmAssist', value }),
    setAssisting: value => dispatch({ type: 'set', key: 'assisting', value }),
    setFilmProjects: value => dispatch({ type: 'set', key: 'filmProjects', value }),
    setFilmProjectId: value => dispatch({ type: 'set', key: 'filmProjectId', value }),
    setFilmProject: value => dispatch({ type: 'set', key: 'filmProject', value }),
    setShotDraft: value => dispatch({ type: 'set', key: 'shotDraft', value }),
    setTakeDraft: value => dispatch({ type: 'set', key: 'takeDraft', value }),
    setFilmTab: value => dispatch({ type: 'set', key: 'filmTab', value }),
    setFilmReview: value => dispatch({ type: 'set', key: 'filmReview', value }),
    setContinuityReport: value => dispatch({ type: 'set', key: 'continuityReport', value }),
    setAssetUploadShotId: value => dispatch({ type: 'set', key: 'assetUploadShotId', value }),
    setUploadingAsset: value => dispatch({ type: 'set', key: 'uploadingAsset', value }),
    setStoryDraft: value => dispatch({ type: 'set', key: 'storyDraft', value }),
    setCharacterDraft: value => dispatch({ type: 'set', key: 'characterDraft', value }),
    setSelectedSceneId: value => dispatch({ type: 'set', key: 'selectedSceneId', value }),
    setSceneDraft: value => dispatch({ type: 'set', key: 'sceneDraft', value }),
    setProductionTool: value => dispatch({ type: 'set', key: 'productionTool', value }),
    setEditDraft: value => dispatch({ type: 'set', key: 'editDraft', value }),
    setEffectDraft: value => dispatch({ type: 'set', key: 'effectDraft', value }),
    setAudioDraft: value => dispatch({ type: 'set', key: 'audioDraft', value }),
    setWorkspaceTool: value => dispatch({ type: 'set', key: 'workspaceTool', value }),
    setRoute: value => dispatch({ type: 'set', key: 'route', value }),
    setDensity: value => dispatch({ type: 'set', key: 'density', value }),
    setNotice: value => dispatch({ type: 'set', key: 'notice', value }),
    setProgress: value => dispatch({ type: 'set', key: 'progress', value }),
    setSelectedLayer: value => dispatch({ type: 'set', key: 'selectedLayer', value }),
    setJobCost: value => dispatch({ type: 'set', key: 'jobCost', value }),
    setActiveJobId: value => dispatch({ type: 'set', key: 'activeJobId', value }),
    setRetryJobId: value => dispatch({ type: 'set', key: 'retryJobId', value }),
    setAuthenticated: value => dispatch({ type: 'set', key: 'authenticated', value }),
    setAuthReady: value => dispatch({ type: 'set', key: 'authReady', value }),
    setLoginPassword: value => dispatch({ type: 'set', key: 'loginPassword', value }),
    setLoginEmail: value => dispatch({ type: 'set', key: 'loginEmail', value }),
    setLoginError: value => dispatch({ type: 'set', key: 'loginError', value }),
    setAuthMode: value => dispatch({ type: 'set', key: 'authMode', value }),
  };
}
